package org.atoiks.games.framework2d;

public enum KeyCode {

    KEY_0, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9,
    KEY_KP0, KEY_KP1, KEY_KP2, KEY_KP3, KEY_KP4,
    KEY_KP5, KEY_KP6, KEY_KP7, KEY_KP8, KEY_KP9,

    KEY_A, KEY_B, KEY_C, KEY_D, KEY_E, KEY_F, KEY_G,
    KEY_H, KEY_I, KEY_J, KEY_K, KEY_L, KEY_M, KEY_N,
    KEY_O, KEY_P, KEY_Q, KEY_R, KEY_S, KEY_T, KEY_U,
    KEY_V, KEY_W, KEY_X, KEY_Y, KEY_Z,

    KEY_SEMICOLON, KEY_COMMA, KEY_PERIOD, KEY_LBRACKET, KEY_RBRACKET,
    KEY_SLASH, KEY_BACKSLASH, KEY_GRAVE_ACCENT, KEY_APOSTROPHE,
    KEY_EQUAL, KEY_MINUS,

    KEY_SPACE, KEY_TAB, KEY_ESCAPE, KEY_ENTER,
    KEY_BACKSPACE, KEY_DELETE,

    KEY_KP_DECIMAL, KEY_KP_EQUAL, KEY_KP_ENTER,
    KEY_KP_ADD, KEY_KP_SUBTRACT, KEY_KP_MULTIPLY, KEY_KP_DIVIDE,

    KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8,
    KEY_F9, KEY_F10, KEY_F11, KEY_F12, KEY_F13, KEY_F14, KEY_F15, KEY_F16,
    KEY_F17, KEY_F18, KEY_F19, KEY_F20, KEY_F21, KEY_F22, KEY_F23, KEY_F24,

    KEY_UP, KEY_DOWN, KEY_LEFT, KEY_RIGHT,

    KEY_PAGE_UP, KEY_PAGE_DOWN, KEY_HOME, KEY_END,
    KEY_INSERT, KEY_MENU, KEY_PAUSE, KEY_PRINTSCREEN,

    KEY_CAPS_LOCK, KEY_SCROLL_LOCK, KEY_NUM_LOCK,

    KEY_LSHIFT, KEY_RSHIFT, KEY_LCTRL, KEY_RCTRL,
    KEY_LALT, KEY_RALT, KEY_LSUPER, KEY_RSUPER,

    KEY_UNDEFINED;

    public String getKeyString() {
        return this.toString().substring(4);
    }
}
